#pragma once
// clang-format off

#ifndef errmap
#define errmap(...)
#endif

errmap(0, EOK, "Operation completed successfully")
errmap(1, EPERM, "Operation not permitted")
errmap(2, ENOENT, "No such file or directory")
errmap(3, ESRCH, "No such process")
errmap(4, EINTR, "Interrupted system call")
errmap(5, EIO, "I/O error")
errmap(6, ENXIO, "No such device or address")
errmap(7, E2BIG, "Argument list too long")
errmap(8, ENOEXEC, "Exec format error")
errmap(9, EBADF, "Bad file number")
errmap(10, ECHILD, "No child processes")
errmap(11, EAGAIN, "Try again")
errmap(12, ENOMEM, "Out of memory")
errmap(13, EACCES, "Permission denied")
errmap(14, EFAULT, "Bad address")
errmap(15, ENOTBLK, "Block device required")
errmap(16, EBUSY, "Device or resource busy")
errmap(17, EEXIST, "File exists")
errmap(18, EXDEV, "Cross-device link")
errmap(19, ENODEV, "No such device")
errmap(20, ENOTDIR, "Not a directory")
errmap(21, EISDIR, "Is a directory")
errmap(22, EINVAL, "Invalid argument")
errmap(23, ENFILE, "File table overflow")
errmap(24, EMFILE, "Too many open files")
errmap(25, ENOTTY, "Not a typewriter")
errmap(26, ETXTBSY, "Text file busy")
errmap(27, EFBIG, "File too large")
errmap(28, ENOSPC, "No space left on device")
errmap(29, ESPIPE, "Illegal seek")
errmap(30, EROFS, "Read-only file system")
errmap(31, EMLINK, "Too many links")
errmap(32, EPIPE, "Broken pipe")
errmap(33, EDOM, "Math argument out of domain of func")
errmap(34, ERANGE, "Math result not representable")
errmap(35, EUNIMPL, "Unimplemented")
errmap(36, EUNKERR, "Unknown error")
